//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS.DbDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionsExpiration
    {
        public int ID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Symbol { get; set; }
        public bool IsActive { get; set; }
        public string SessionKey { get; set; }
    }
}
